# .mega-linter.yml
FLAVOR: salesforce

DISABLE_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_KICS
  - REPOSITORY_CHECKOV
  - SALESFORCE_LIGHTNING_FLOW_SCANNER  # Optional, enable if you use flows

SPELL_CSPELL_CONFIG_FILE: .cspell.json
