FLAVOR: salesforce

# Disable false-positive linters or unnecessary ones
DISABLE_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_KICS
  - REPOSITORY_CHECKOV
  - SALESFORCE_LIGHTNING_FLOW_SCANNER  # Optional

# Allow Shivam and other custom words
SPELL_CSPELL_CONFIG_FILE: .cspell.json
