FLAVOR: salesforce

# Explicitly enable APEX linter (optional but ensures activation)
APEX:
  ENABLE: true
# Optional, restrict scope of scan
FILTER_REGEX_INCLUDE: 'force-app/main/default/classes/.*\.cls'
