name: MegaLinter

permissions:
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main, abhishek ]
  pull_request:
    branches: [ main, abhishek ]

jobs:
  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
