name: MegaLinter

on: [push, pull_request]

jobs:
  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Optional: Set up Node.js for Salesforce CLI
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ✅ Cache global npm modules (Salesforce CLI + plugins)
      - name: Cache global npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      # Install Salesforce scanner plugins
      - name: Install Salesforce Plugins
        run: |
          sf plugins install @salesforce/sfdx-scanner
          sf plugins install @salesforce/sfdx-plugin-lwc-test

      # Run MegaLinter with Salesforce flavor and pinned SHA
      - name: MegaLinter
        uses: oxsecurity/megalinter@bacb5f8674e3730b904ca4d20c8bd477bc51b1a7
